apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: step1
spec:
  containers:
  - image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
    name: multitool
