@startmindmap kubectl
<style>

node {
    Margin 4
    LineThickness 1.0
    RoundCorner 0
    Shadowing 0.0
}

rootNode {
    Margin 12
    HorizontalAlignment center
    BackgroundColor gold
    LineThickness 1.0
}

leafNode {
    LineColor gold
    RoundCorner 0
    Padding 6
    Margin 4
}

</style>
+ kubectl
++_ version
++_ exec
++_ logs
++_ apply
++ delete
++ get
++ describe
++ edit

--_ cordon / uncordon
--_ drain
--_ taint

++_ port-forward
++_ label
++_ annotate
++_ config

++_ run
++_ set
++_ explain
++_ create
++_ expose
@endmindmap
